# Generated by Django 4.2.7 on 2023-11-22 18:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chat', '0002_delete_userfriendmessagesocket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriendSocket',
            fields=[
                ('userfriend', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserfriendMessageSocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/MessageMedia/Photos')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/MessageVideo/Videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('userfriend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.userfriendsocket')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
