# Generated by Django 4.2.7 on 2023-11-25 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_websocketuserfriendmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketUserfriendsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('time', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/MessageMedia/Photos')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/MessageVideo/Videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('userfriend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.userfriendsocket')),
            ],
        ),
        migrations.RemoveField(
            model_name='websocketuserfriendmessage',
            name='userfriend',
        ),
        migrations.DeleteModel(
            name='UserfriendMessageSocket',
        ),
        migrations.DeleteModel(
            name='WebSocketUserfriendMessage',
        ),
    ]
