# Generated by Django 4.2.7 on 2023-11-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_websocketuserfriendsmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriendsocket',
            name='userfriend',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
