# Generated by Django 4.2.7 on 2023-12-17 09:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_alter_userfriendsocket_userfriend'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocketGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='websocketuserfriendsmessage',
            name='delete_access',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='websocketuserfriendsmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='MessageMedia/Photos'),
        ),
        migrations.AlterField(
            model_name='websocketuserfriendsmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='MessageVideo/Videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.CreateModel(
            name='SocketGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('time', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='GroupPhotos/Photos')),
                ('video', models.FileField(blank=True, null=True, upload_to='GroupVideo/Videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.socketgroup')),
            ],
        ),
    ]
