# Generated by Django 4.2.7 on 2023-11-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profileuser_profile_binary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_img',
            field=models.FileField(blank=True, null=True, upload_to='Profiles'),
        ),
        migrations.DeleteModel(
            name='profilemodel',
        ),
    ]
